
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.yAYcHEo0PvA.2018.O/ck=xjs.s.eDG_pTHyx4g.L.B1.O/am=AIQjEAIAAAACAABACAAVgAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAIAAAAAAAAAQAIAxQRQEkJRPAAAAAAQnASA7AAAAAPABfMSpAoAAAMCAABAQJAAAAAABAAEAAQAwAwIQEFIBACgAAAFBCAEABACwAQCARICACIL3_acBAwAAGQAAAABAAABOBQDEQQIQAIADAACOuBAgEQAHABC6C5AAAAAoQQAAAAgAAAoAAAAQAAAgAohDMAyAQAWAARwBAAAAABkAIBAAAQAICBACADAAoBAAECAAAPQAgAB8ADZEA0QAACgAAxgQAAACQAI_bQAAAQAAnAQAACAAKAKAY4QCIAAAAAAAACAPAI8HYEhBAQAAAAAAAAAAAAAAQAASBHMg_YIAAQAAAAAAAAAAAAAAAAAAKYImrjUAQA/d=0/dg=0/br=1/ujg=1/rs=ACT90oHOjXLbGk0u2i6O0q59wbaotmLfEw/m=syho,aLUfP,wQlYve,sy8hj,sy45a,sy46r,sy8h3,sy8h2,sy5qv,sy1nb,sy1n3,sy8c,sy1n4,pKhWu,sy7o6,pHXghd?xjs=s3",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/async/bgasy?ei=8yL0Z8b6GYOyhbIP5ezF8Q8&opi=89978449&yv=3&cs=0&async=_fmt:jspb",
  "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.yAYcHEo0PvA.2018.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAARQEgAAAAAAAAAAAASAAAAAAAAAATAAAAAAAAMCAABAQJAAAAAABAAAAAAAwAwAQEFABACgAAAAAAAAAAAAAAQAAAICACID3_aMBAAAAAAAAAAAAAAAAAAAEQAIAAIABAAAAuAAAEAAHABCyCxAAAAAAAAAAAAgAAAAAAAAQAAAAAAhAAAAAAAUAAAAAAAAAAAgAAAAAAAAACAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAQAA_AAAAAAAAHAAAACAAAACAY4QCIAAAAAAAACAPAI8HYEhBAQAAAAAAAAAAAAAAQAASBHMg_YIAAQAAAAAAAAAAAAAAAAAAKYImrjUAQA/d=0/dg=0/br=1/rs=ACT90oH57-a8QxO31QRuEKDVG72fNCyT0A/m=sb_wiz,aa,abd,sy16k,syxm,syxl,syxe,syxk,syxn,async,sy19a,bgd,sy8dd,foot,sy24t,kyn,sy174,sy23c,lli,sf,sy18q,sy18r,sy7up,sonic,sy807,sy1ot,sygy,sy3ty,sy18g,sy17f,sy149,syv4,syy8,syy6,syy5,syy3,syy2,syy7,sy1wb,sy1wc,sy148,syyj,sybd,sya7,sya6,sya5,sya4,spch,tl?xjs=s4"
];
  
  